- hosts: all
  become: true

  tasks:
    - name: ensure a container is running
      docker_container:
        name: my_container12
        state: started
        image: priyanshu18/quote-app
        pull: true
        ports:
          - "3000:3000"
        
